#**10. Data Analytics - III**#

In [41]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, classification_report

In [42]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datasets/Iris.csv")

In [43]:
df.shape

(150, 6)

In [44]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

###**Simple Naïve Bayes Classification Algorithm**###

In [45]:
X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species']

In [46]:
#Split dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [47]:
#Initialize the Classifier
gnb = GaussianNB()

In [48]:
#Train the Classifier
gnb.fit(X_train, y_train)

GaussianNB()

In [49]:
#Predictions
y_pred = gnb.predict(X_test)

In [50]:
#Print actual values and predictions
print("Actual Values vs Predictions:\n")
for i in range(len(y_test)):
    print("Actual: {:<17}   Predicted: {}".format(y_test.iloc[i], y_pred[i]))

Actual Values vs Predictions:

Actual: Iris-versicolor     Predicted: Iris-versicolor
Actual: Iris-setosa         Predicted: Iris-setosa
Actual: Iris-virginica      Predicted: Iris-virginica
Actual: Iris-versicolor     Predicted: Iris-versicolor
Actual: Iris-versicolor     Predicted: Iris-versicolor
Actual: Iris-setosa         Predicted: Iris-setosa
Actual: Iris-versicolor     Predicted: Iris-versicolor
Actual: Iris-virginica      Predicted: Iris-virginica
Actual: Iris-versicolor     Predicted: Iris-versicolor
Actual: Iris-versicolor     Predicted: Iris-versicolor
Actual: Iris-virginica      Predicted: Iris-virginica
Actual: Iris-setosa         Predicted: Iris-setosa
Actual: Iris-setosa         Predicted: Iris-setosa
Actual: Iris-setosa         Predicted: Iris-setosa
Actual: Iris-setosa         Predicted: Iris-setosa
Actual: Iris-versicolor     Predicted: Iris-virginica
Actual: Iris-virginica      Predicted: Iris-virginica
Actual: Iris-versicolor     Predicted: Iris-versicolor
Actual: 

###**Compute Confusion Matrix to find TP, FP, TN, FN, Accuracy, Precision, Error Rate & Recall**###

In [51]:
conf_matrix = confusion_matrix(y_test, y_pred)

TP = conf_matrix[1, 1]
FP = conf_matrix[0, 1]
TN = conf_matrix[0, 0]
FN = conf_matrix[1, 0]

In [52]:
accuracy = (TP + TN) / (TP + FP + TN + FN)
error_rate = (FP + FN) / (TP + FP + TN + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)

In [53]:
print("Confusion Matrix:\n")
print(conf_matrix)
print("\nTrue Positives:", TP)
print("\nFalse Positives:", FP)
print("\nTrue Negatives:", TN)
print("\nFalse Negatives:", FN)
print("\n\nAccuracy:", accuracy)
print("\nError Rate:", error_rate)
print("\nPrecision:", precision)
print("\nRecall:", recall)

Confusion Matrix:

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]

True Positives: 12

False Positives: 0

True Negatives: 19

False Negatives: 0


Accuracy: 1.0

Error Rate: 0.0

Precision: 1.0

Recall: 1.0


###**Classification Report**###

In [54]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.93      1.00      0.96        13

       accuracy                           0.98        45
      macro avg       0.98      0.97      0.97        45
   weighted avg       0.98      0.98      0.98        45





---

